[versions]
tg-bot = "7.4.0"
ksp = "2.0.21-1.0.26"

kotlin = "2.0.21"

[libraries]


[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }