[versions]
tg-bot = "5.3.2"
spring-boot = "3.2.5"
spring-dependency-management = "1.1.4"
ksp = "1.9.23-1.0.20"

kotlin = "1.9.23"

[libraries]
tg-bot = { module = "eu.vendeli:telegram-bot", version.ref = "tg-bot" }
tg-ksp = { module = "eu.vendeli:ksp", version.ref = "tg-bot" }
tg-spring-starter = { module = "eu.vendeli:spring-ktgram-starter", version.ref = "tg-bot" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

