[versions]
tg-bot = "5.3.1"
ktor = "2.2.4"
logback = "1.5.6"
ksp = "1.9.23-1.0.20"

kotlin = "1.9.23"

[libraries]
tg-bot = { module = "eu.vendeli:telegram-bot", version.ref = "tg-bot" }
tg-ksp = { module = "eu.vendeli:ksp", version.ref = "tg-bot" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }