[versions]
tg-bot = "7.3.1"
ksp = "2.0.20-1.0.25"

kotlin = "2.0.20"

[libraries]


[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }