[versions]
tg-bot = "7.6.1"
ksp = "2.1.0-1.0.29"

kotlin = "2.1.0"

[libraries]


[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }