[versions]
tg-bot = "8.4.1"
ksp = "2.3.3"

kotlin = "2.2.21"

[libraries]


[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }