[versions]
spring-boot = "4.0.2"
spring-dependency-management = "1.1.7"
tg-bot = "9.1.0"
ksp = "2.3.4"

kotlin = "2.3.0"

[libraries]
tg-spring-starter = { module = "eu.vendeli:spring-ktgram-starter", version.ref = "tg-bot" }

[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

