[versions]
tg-bot = "9.2.1"
ksp = "2.3.6"

kotlin = "2.3.10"

[libraries]

[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }