[versions]
logback = "1.5.8"
tg-bot = "7.2.2"
ksp = "2.0.20-1.0.25"

kotlin = "2.0.20"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }